### ISSUE TITLE
Unescaping?

### ISSUE THREAD

**Issue by chriseppstein** [mathiasbynens/cssesc#14]
I looked all over the internet for a javascript library that could handle unescaping CSS escape sequences and did not find one in javascript. Maybe my google-fu is bad?

So... I wrote one for my needs. I think it would be nicely paired with this library since round-tripping escapes into characters and back seems like a fairly common use case. I will submit a PR if you're interested. The basic function is the following:

```js
const HEX_ESC = /\\(?:([0-9a-fA-F]{6})|([0-9a-fA-F]{1,5})(?: |(?![0-9a-fA-F])))/g;
const OTHER_ESC = /\\(.)/g;
function unesc (str) {
    str = str.replace(HEX_ESC, (_, hex1, hex2) => {
        let hex = hex1 || hex2;
        let code = parseInt(hex, 16);
        return String.fromCharCode(code);
    });
    str = str.replace(OTHER_ESC, (_, char) => char);
    return str;
}
```

**Comment by mathiasbynens** [comment]
There’s several issues with this approach:

* It fails for astral symbols due to the use of `String.fromCharCode`. E.g. ``unesc(String.raw`\1D306`)`` should return `'\u{1D306}'` but doesn’t. Using `String.fromCodePoint` instead would fix this.
* It doesn’t handle odd numbers of backslashes preceding an escape sequence. E.g. ``unesc(String.raw`\\32`)`` should return ``(String.raw`\32`)`` but instead returns ``(String.raw`2`)``. There is no way around this instead of writing a parser.

**Comment by mathiasbynens** [comment]
I'd prefer to keep the cssesc project scoped to just escaping.

The escape parser would be super valuable as a separate project! Please let me know if/when you decide to publish it. I'll happily link to it from the README.

**Comment by alexander-akait** [comment]
@chriseppstein Do you have link on implementation? We need this feature for `css` modules to avoid some problems after interpolation

**Comment by buschtoens** [comment]
I'm also very interested in a CSS unescape tool.

**Comment by buschtoens** [comment]
How "safe" would you say this unescaper is?
https://github.com/postcss/postcss-selector-parser/blob/master/src/util/unesc.js
